// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXnd-XElmnG3ICUWwtttPhNRI_85wM9a8',
    appId: '1:927018569367:web:b51d51dec0da7813b5a3d2',
    messagingSenderId: '927018569367',
    projectId: 'my-app-f45d8',
    authDomain: 'my-app-f45d8.firebaseapp.com',
    storageBucket: 'my-app-f45d8.firebasestorage.app',
    measurementId: 'G-YWL35HX9QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRp3DsScrEMrGGO8NJjo-dVjKjjKxSEk',
    appId: '1:927018569367:android:d6357f1041460a4bb5a3d2',
    messagingSenderId: '927018569367',
    projectId: 'my-app-f45d8',
    storageBucket: 'my-app-f45d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZSg-KhbnkiqWPQOBXvt8Dymyl9sTGQAQ',
    appId: '1:927018569367:ios:fa89b14c21e38428b5a3d2',
    messagingSenderId: '927018569367',
    projectId: 'my-app-f45d8',
    storageBucket: 'my-app-f45d8.firebasestorage.app',
    androidClientId:
        '927018569367-ot890b8umdnoq5t79bgsehocod33jtug.apps.googleusercontent.com',
    iosClientId:
        '927018569367-ov5fltgfoko6prhbdknbo1teev4mmtot.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalWellbeing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZSg-KhbnkiqWPQOBXvt8Dymyl9sTGQAQ',
    appId: '1:927018569367:ios:fa89b14c21e38428b5a3d2',
    messagingSenderId: '927018569367',
    projectId: 'my-app-f45d8',
    storageBucket: 'my-app-f45d8.firebasestorage.app',
    androidClientId:
        '927018569367-ot890b8umdnoq5t79bgsehocod33jtug.apps.googleusercontent.com',
    iosClientId:
        '927018569367-ov5fltgfoko6prhbdknbo1teev4mmtot.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalWellbeing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXnd-XElmnG3ICUWwtttPhNRI_85wM9a8',
    appId: '1:927018569367:web:08da53578a69c3e2b5a3d2',
    messagingSenderId: '927018569367',
    projectId: 'my-app-f45d8',
    authDomain: 'my-app-f45d8.firebaseapp.com',
    storageBucket: 'my-app-f45d8.firebasestorage.app',
    measurementId: 'G-ZFL60VZYHF',
  );
}
